//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.FPMMD_FTQ {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="FPMMD_FTQ.ZWS_OPMS_MASTERDATA")]
    public interface ZWS_OPMS_MASTERDATA {
        
        // CODEGEN: Generating message contract since the operation ZFM_OPMS_MASTER is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_OPMS_MASTERDATA:ZFM_OPMS_MASTERRequest" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse1 ZFM_OPMS_MASTER(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZWS_OPMS_MASTERDATA:ZFM_OPMS_MASTERRequest" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse1> ZFM_OPMS_MASTERAsync(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_OPMS_MASTER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cC_BEGINField;
        
        private string cC_COMPField;
        
        private string cC_ENDField;
        
        private string cS_BEGINField;
        
        private string cS_COMPField;
        
        private string cS_ENDField;
        
        private string dATE_BEGINField;
        
        private string dATE_ENDField;
        
        private string gL_BEGINField;
        
        private string gL_COMPField;
        
        private string gL_ENDField;
        
        private ZOPMSCC[] iT_CCField;
        
        private ZOPMSCS[] iT_CUSTField;
        
        private ZOPMSGL[] iT_GLField;
        
        private ZOPMSIO[] iT_IOField;
        
        private ZOPMSSLP[] iT_SLPField;
        
        private ZOPMSVD[] iT_VENDField;
        
        private string oRDERID_BEGINField;
        
        private string oRDERID_ENDField;
        
        private string sLP_COMPField;
        
        private string sLP_IND_BEGINField;
        
        private string sLP_IND_ENDField;
        
        private string sLP_PKT_BEGINField;
        
        private string sLP_PKT_ENDField;
        
        private string sLP_RAN_BEGINField;
        
        private string sLP_RAN_ENDField;
        
        private string vD_BEGINField;
        
        private string vD_COMPField;
        
        private string vD_ENDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CC_BEGIN {
            get {
                return this.cC_BEGINField;
            }
            set {
                this.cC_BEGINField = value;
                this.RaisePropertyChanged("CC_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CC_COMP {
            get {
                return this.cC_COMPField;
            }
            set {
                this.cC_COMPField = value;
                this.RaisePropertyChanged("CC_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CC_END {
            get {
                return this.cC_ENDField;
            }
            set {
                this.cC_ENDField = value;
                this.RaisePropertyChanged("CC_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CS_BEGIN {
            get {
                return this.cS_BEGINField;
            }
            set {
                this.cS_BEGINField = value;
                this.RaisePropertyChanged("CS_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CS_COMP {
            get {
                return this.cS_COMPField;
            }
            set {
                this.cS_COMPField = value;
                this.RaisePropertyChanged("CS_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CS_END {
            get {
                return this.cS_ENDField;
            }
            set {
                this.cS_ENDField = value;
                this.RaisePropertyChanged("CS_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DATE_BEGIN {
            get {
                return this.dATE_BEGINField;
            }
            set {
                this.dATE_BEGINField = value;
                this.RaisePropertyChanged("DATE_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DATE_END {
            get {
                return this.dATE_ENDField;
            }
            set {
                this.dATE_ENDField = value;
                this.RaisePropertyChanged("DATE_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string GL_BEGIN {
            get {
                return this.gL_BEGINField;
            }
            set {
                this.gL_BEGINField = value;
                this.RaisePropertyChanged("GL_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string GL_COMP {
            get {
                return this.gL_COMPField;
            }
            set {
                this.gL_COMPField = value;
                this.RaisePropertyChanged("GL_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string GL_END {
            get {
                return this.gL_ENDField;
            }
            set {
                this.gL_ENDField = value;
                this.RaisePropertyChanged("GL_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSCC[] IT_CC {
            get {
                return this.iT_CCField;
            }
            set {
                this.iT_CCField = value;
                this.RaisePropertyChanged("IT_CC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSCS[] IT_CUST {
            get {
                return this.iT_CUSTField;
            }
            set {
                this.iT_CUSTField = value;
                this.RaisePropertyChanged("IT_CUST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSGL[] IT_GL {
            get {
                return this.iT_GLField;
            }
            set {
                this.iT_GLField = value;
                this.RaisePropertyChanged("IT_GL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSIO[] IT_IO {
            get {
                return this.iT_IOField;
            }
            set {
                this.iT_IOField = value;
                this.RaisePropertyChanged("IT_IO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSSLP[] IT_SLP {
            get {
                return this.iT_SLPField;
            }
            set {
                this.iT_SLPField = value;
                this.RaisePropertyChanged("IT_SLP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSVD[] IT_VEND {
            get {
                return this.iT_VENDField;
            }
            set {
                this.iT_VENDField = value;
                this.RaisePropertyChanged("IT_VEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ORDERID_BEGIN {
            get {
                return this.oRDERID_BEGINField;
            }
            set {
                this.oRDERID_BEGINField = value;
                this.RaisePropertyChanged("ORDERID_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ORDERID_END {
            get {
                return this.oRDERID_ENDField;
            }
            set {
                this.oRDERID_ENDField = value;
                this.RaisePropertyChanged("ORDERID_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SLP_COMP {
            get {
                return this.sLP_COMPField;
            }
            set {
                this.sLP_COMPField = value;
                this.RaisePropertyChanged("SLP_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SLP_IND_BEGIN {
            get {
                return this.sLP_IND_BEGINField;
            }
            set {
                this.sLP_IND_BEGINField = value;
                this.RaisePropertyChanged("SLP_IND_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SLP_IND_END {
            get {
                return this.sLP_IND_ENDField;
            }
            set {
                this.sLP_IND_ENDField = value;
                this.RaisePropertyChanged("SLP_IND_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string SLP_PKT_BEGIN {
            get {
                return this.sLP_PKT_BEGINField;
            }
            set {
                this.sLP_PKT_BEGINField = value;
                this.RaisePropertyChanged("SLP_PKT_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string SLP_PKT_END {
            get {
                return this.sLP_PKT_ENDField;
            }
            set {
                this.sLP_PKT_ENDField = value;
                this.RaisePropertyChanged("SLP_PKT_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string SLP_RAN_BEGIN {
            get {
                return this.sLP_RAN_BEGINField;
            }
            set {
                this.sLP_RAN_BEGINField = value;
                this.RaisePropertyChanged("SLP_RAN_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string SLP_RAN_END {
            get {
                return this.sLP_RAN_ENDField;
            }
            set {
                this.sLP_RAN_ENDField = value;
                this.RaisePropertyChanged("SLP_RAN_END");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string VD_BEGIN {
            get {
                return this.vD_BEGINField;
            }
            set {
                this.vD_BEGINField = value;
                this.RaisePropertyChanged("VD_BEGIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string VD_COMP {
            get {
                return this.vD_COMPField;
            }
            set {
                this.vD_COMPField = value;
                this.RaisePropertyChanged("VD_COMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string VD_END {
            get {
                return this.vD_ENDField;
            }
            set {
                this.vD_ENDField = value;
                this.RaisePropertyChanged("VD_END");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZOPMSCC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kOKRSField;
        
        private string kOSTLField;
        
        private string lTEXTField;
        
        private string bKZKPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KOKRS {
            get {
                return this.kOKRSField;
            }
            set {
                this.kOKRSField = value;
                this.RaisePropertyChanged("KOKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
                this.RaisePropertyChanged("KOSTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LTEXT {
            get {
                return this.lTEXTField;
            }
            set {
                this.lTEXTField = value;
                this.RaisePropertyChanged("LTEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string BKZKP {
            get {
                return this.bKZKPField;
            }
            set {
                this.bKZKPField = value;
                this.RaisePropertyChanged("BKZKP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZOPMSVD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string lIFNRField;
        
        private string nAME1Field;
        
        private string lOEVMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
                this.RaisePropertyChanged("LIFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOEVM {
            get {
                return this.lOEVMField;
            }
            set {
                this.lOEVMField = value;
                this.RaisePropertyChanged("LOEVM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZOPMSSLP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zBUKRSField;
        
        private string zKDRGIField;
        
        private string zKDRGNField;
        
        private string zKDPKTField;
        
        private string zKDPK2Field;
        
        private string zTHNPBField;
        
        private string zTHPTSField;
        
        private string zGPCOSField;
        
        private string zPSND1Field;
        
        private string zPSND2Field;
        
        private string zPSND3Field;
        
        private string zPSND4Field;
        
        private string zPSND5Field;
        
        private string zPSND6Field;
        
        private string zTHTMBField;
        
        private decimal zBLPN2Field;
        
        private decimal zBLOT2Field;
        
        private string zPKPBGField;
        
        private string zTHTHPField;
        
        private string zTHMTMField;
        
        private decimal zJMLTFField;
        
        private decimal zLKWTNField;
        
        private decimal zLSKBHField;
        
        private decimal zLSKBFField;
        
        private decimal zLSKBPField;
        
        private string zJSTNMField;
        
        private string zKDBLKField;
        
        private string zJENKIField;
        
        private decimal zLDLTFField;
        
        private decimal zLDLTPField;
        
        private string zJSBLKField;
        
        private string zJSKWSField;
        
        private string zBLPR3Field;
        
        private decimal zBLKWUField;
        
        private decimal zBLKWRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ZBUKRS {
            get {
                return this.zBUKRSField;
            }
            set {
                this.zBUKRSField = value;
                this.RaisePropertyChanged("ZBUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ZKDRGI {
            get {
                return this.zKDRGIField;
            }
            set {
                this.zKDRGIField = value;
                this.RaisePropertyChanged("ZKDRGI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ZKDRGN {
            get {
                return this.zKDRGNField;
            }
            set {
                this.zKDRGNField = value;
                this.RaisePropertyChanged("ZKDRGN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ZKDPKT {
            get {
                return this.zKDPKTField;
            }
            set {
                this.zKDPKTField = value;
                this.RaisePropertyChanged("ZKDPKT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ZKDPK2 {
            get {
                return this.zKDPK2Field;
            }
            set {
                this.zKDPK2Field = value;
                this.RaisePropertyChanged("ZKDPK2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string ZTHNPB {
            get {
                return this.zTHNPBField;
            }
            set {
                this.zTHNPBField = value;
                this.RaisePropertyChanged("ZTHNPB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string ZTHPTS {
            get {
                return this.zTHPTSField;
            }
            set {
                this.zTHPTSField = value;
                this.RaisePropertyChanged("ZTHPTS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string ZGPCOS {
            get {
                return this.zGPCOSField;
            }
            set {
                this.zGPCOSField = value;
                this.RaisePropertyChanged("ZGPCOS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string ZPSND1 {
            get {
                return this.zPSND1Field;
            }
            set {
                this.zPSND1Field = value;
                this.RaisePropertyChanged("ZPSND1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ZPSND2 {
            get {
                return this.zPSND2Field;
            }
            set {
                this.zPSND2Field = value;
                this.RaisePropertyChanged("ZPSND2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ZPSND3 {
            get {
                return this.zPSND3Field;
            }
            set {
                this.zPSND3Field = value;
                this.RaisePropertyChanged("ZPSND3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string ZPSND4 {
            get {
                return this.zPSND4Field;
            }
            set {
                this.zPSND4Field = value;
                this.RaisePropertyChanged("ZPSND4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string ZPSND5 {
            get {
                return this.zPSND5Field;
            }
            set {
                this.zPSND5Field = value;
                this.RaisePropertyChanged("ZPSND5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string ZPSND6 {
            get {
                return this.zPSND6Field;
            }
            set {
                this.zPSND6Field = value;
                this.RaisePropertyChanged("ZPSND6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string ZTHTMB {
            get {
                return this.zTHTMBField;
            }
            set {
                this.zTHTMBField = value;
                this.RaisePropertyChanged("ZTHTMB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal ZBLPN2 {
            get {
                return this.zBLPN2Field;
            }
            set {
                this.zBLPN2Field = value;
                this.RaisePropertyChanged("ZBLPN2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal ZBLOT2 {
            get {
                return this.zBLOT2Field;
            }
            set {
                this.zBLOT2Field = value;
                this.RaisePropertyChanged("ZBLOT2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string ZPKPBG {
            get {
                return this.zPKPBGField;
            }
            set {
                this.zPKPBGField = value;
                this.RaisePropertyChanged("ZPKPBG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string ZTHTHP {
            get {
                return this.zTHTHPField;
            }
            set {
                this.zTHTHPField = value;
                this.RaisePropertyChanged("ZTHTHP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string ZTHMTM {
            get {
                return this.zTHMTMField;
            }
            set {
                this.zTHMTMField = value;
                this.RaisePropertyChanged("ZTHMTM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal ZJMLTF {
            get {
                return this.zJMLTFField;
            }
            set {
                this.zJMLTFField = value;
                this.RaisePropertyChanged("ZJMLTF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal ZLKWTN {
            get {
                return this.zLKWTNField;
            }
            set {
                this.zLKWTNField = value;
                this.RaisePropertyChanged("ZLKWTN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public decimal ZLSKBH {
            get {
                return this.zLSKBHField;
            }
            set {
                this.zLSKBHField = value;
                this.RaisePropertyChanged("ZLSKBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public decimal ZLSKBF {
            get {
                return this.zLSKBFField;
            }
            set {
                this.zLSKBFField = value;
                this.RaisePropertyChanged("ZLSKBF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public decimal ZLSKBP {
            get {
                return this.zLSKBPField;
            }
            set {
                this.zLSKBPField = value;
                this.RaisePropertyChanged("ZLSKBP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string ZJSTNM {
            get {
                return this.zJSTNMField;
            }
            set {
                this.zJSTNMField = value;
                this.RaisePropertyChanged("ZJSTNM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string ZKDBLK {
            get {
                return this.zKDBLKField;
            }
            set {
                this.zKDBLKField = value;
                this.RaisePropertyChanged("ZKDBLK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string ZJENKI {
            get {
                return this.zJENKIField;
            }
            set {
                this.zJENKIField = value;
                this.RaisePropertyChanged("ZJENKI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal ZLDLTF {
            get {
                return this.zLDLTFField;
            }
            set {
                this.zLDLTFField = value;
                this.RaisePropertyChanged("ZLDLTF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal ZLDLTP {
            get {
                return this.zLDLTPField;
            }
            set {
                this.zLDLTPField = value;
                this.RaisePropertyChanged("ZLDLTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string ZJSBLK {
            get {
                return this.zJSBLKField;
            }
            set {
                this.zJSBLKField = value;
                this.RaisePropertyChanged("ZJSBLK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string ZJSKWS {
            get {
                return this.zJSKWSField;
            }
            set {
                this.zJSKWSField = value;
                this.RaisePropertyChanged("ZJSKWS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string ZBLPR3 {
            get {
                return this.zBLPR3Field;
            }
            set {
                this.zBLPR3Field = value;
                this.RaisePropertyChanged("ZBLPR3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public decimal ZBLKWU {
            get {
                return this.zBLKWUField;
            }
            set {
                this.zBLKWUField = value;
                this.RaisePropertyChanged("ZBLKWU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public decimal ZBLKWR {
            get {
                return this.zBLKWRField;
            }
            set {
                this.zBLKWRField = value;
                this.RaisePropertyChanged("ZBLKWR");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZOPMSIO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kOKRSField;
        
        private string bUKRSField;
        
        private string aUFNRField;
        
        private string kTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string KOKRS {
            get {
                return this.kOKRSField;
            }
            set {
                this.kOKRSField = value;
                this.RaisePropertyChanged("KOKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
                this.RaisePropertyChanged("AUFNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string KTEXT {
            get {
                return this.kTEXTField;
            }
            set {
                this.kTEXTField = value;
                this.RaisePropertyChanged("KTEXT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZOPMSGL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string sAKNRField;
        
        private string tXT50Field;
        
        private string xLOEBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string SAKNR {
            get {
                return this.sAKNRField;
            }
            set {
                this.sAKNRField = value;
                this.RaisePropertyChanged("SAKNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TXT50 {
            get {
                return this.tXT50Field;
            }
            set {
                this.tXT50Field = value;
                this.RaisePropertyChanged("TXT50");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string XLOEB {
            get {
                return this.xLOEBField;
            }
            set {
                this.xLOEBField = value;
                this.RaisePropertyChanged("XLOEB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZOPMSCS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bUKRSField;
        
        private string kUNNRField;
        
        private string nAME1Field;
        
        private string lOEVMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
                this.RaisePropertyChanged("BUKRS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
                this.RaisePropertyChanged("KUNNR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
                this.RaisePropertyChanged("NAME1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOEVM {
            get {
                return this.lOEVMField;
            }
            set {
                this.lOEVMField = value;
                this.RaisePropertyChanged("LOEVM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZFM_OPMS_MASTERResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZOPMSCC[] iT_CCField;
        
        private ZOPMSCS[] iT_CUSTField;
        
        private ZOPMSGL[] iT_GLField;
        
        private ZOPMSIO[] iT_IOField;
        
        private ZOPMSSLP[] iT_SLPField;
        
        private ZOPMSVD[] iT_VENDField;
        
        private BAPIRET2[] rETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSCC[] IT_CC {
            get {
                return this.iT_CCField;
            }
            set {
                this.iT_CCField = value;
                this.RaisePropertyChanged("IT_CC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSCS[] IT_CUST {
            get {
                return this.iT_CUSTField;
            }
            set {
                this.iT_CUSTField = value;
                this.RaisePropertyChanged("IT_CUST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSGL[] IT_GL {
            get {
                return this.iT_GLField;
            }
            set {
                this.iT_GLField = value;
                this.RaisePropertyChanged("IT_GL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSIO[] IT_IO {
            get {
                return this.iT_IOField;
            }
            set {
                this.iT_IOField = value;
                this.RaisePropertyChanged("IT_IO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSSLP[] IT_SLP {
            get {
                return this.iT_SLPField;
            }
            set {
                this.iT_SLPField = value;
                this.RaisePropertyChanged("IT_SLP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZOPMSVD[] IT_VEND {
            get {
                return this.iT_VENDField;
            }
            set {
                this.iT_VENDField = value;
                this.RaisePropertyChanged("IT_VEND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] RETURN {
            get {
                return this.rETURNField;
            }
            set {
                this.rETURNField = value;
                this.RaisePropertyChanged("RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_OPMS_MASTERRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTER ZFM_OPMS_MASTER;
        
        public ZFM_OPMS_MASTERRequest() {
        }
        
        public ZFM_OPMS_MASTERRequest(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTER ZFM_OPMS_MASTER) {
            this.ZFM_OPMS_MASTER = ZFM_OPMS_MASTER;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZFM_OPMS_MASTERResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse ZFM_OPMS_MASTERResponse;
        
        public ZFM_OPMS_MASTERResponse1() {
        }
        
        public ZFM_OPMS_MASTERResponse1(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse ZFM_OPMS_MASTERResponse) {
            this.ZFM_OPMS_MASTERResponse = ZFM_OPMS_MASTERResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_OPMS_MASTERDATAChannel : MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_OPMS_MASTERDATAClient : System.ServiceModel.ClientBase<MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA>, MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA {
        
        public ZWS_OPMS_MASTERDATAClient() {
        }
        
        public ZWS_OPMS_MASTERDATAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_OPMS_MASTERDATAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_OPMS_MASTERDATAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_OPMS_MASTERDATAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse1 MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA.ZFM_OPMS_MASTER(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest request) {
            return base.Channel.ZFM_OPMS_MASTER(request);
        }
        
        public MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse ZFM_OPMS_MASTER(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTER ZFM_OPMS_MASTER1) {
            MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest inValue = new MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest();
            inValue.ZFM_OPMS_MASTER = ZFM_OPMS_MASTER1;
            MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse1 retVal = ((MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA)(this)).ZFM_OPMS_MASTER(inValue);
            return retVal.ZFM_OPMS_MASTERResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse1> MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA.ZFM_OPMS_MASTERAsync(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest request) {
            return base.Channel.ZFM_OPMS_MASTERAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERResponse1> ZFM_OPMS_MASTERAsync(MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTER ZFM_OPMS_MASTER) {
            MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest inValue = new MVC_SYSTEM.FPMMD_FTQ.ZFM_OPMS_MASTERRequest();
            inValue.ZFM_OPMS_MASTER = ZFM_OPMS_MASTER;
            return ((MVC_SYSTEM.FPMMD_FTQ.ZWS_OPMS_MASTERDATA)(this)).ZFM_OPMS_MASTERAsync(inValue);
        }
    }
}
