//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResWorkerTransac {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResWorkerTransac() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResWorkerTransac", typeof(GlobalResWorkerTransac).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH.
        /// </summary>
        public static string ftrTotal {
            get {
                return ResourceManager.GetString("ftrTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviti.
        /// </summary>
        public static string hdrAktvt {
            get {
                return ResourceManager.GetString("hdrAktvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit (RM).
        /// </summary>
        public static string hdrDbt {
            get {
                return ResourceManager.GetString("hdrDbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. P2/P3/Invois.
        /// </summary>
        public static string hdrInvois {
            get {
                return ResourceManager.GetString("hdrInvois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Stok.
        /// </summary>
        public static string hdrKodStok {
            get {
                return ResourceManager.GetString("hdrKodStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit (RM).
        /// </summary>
        public static string hdrKrdt {
            get {
                return ResourceManager.GetString("hdrKrdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keterangan Aktiviti.
        /// </summary>
        public static string hdrKtrgn {
            get {
                return ResourceManager.GetString("hdrKtrgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuantiti.
        /// </summary>
        public static string hdrKuantiti {
            get {
                return ResourceManager.GetString("hdrKuantiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejar.
        /// </summary>
        public static string hdrLejar {
            get {
                return ResourceManager.GetString("hdrLejar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoA / Tetap Kend..
        /// </summary>
        public static string hdrNoA {
            get {
                return ResourceManager.GetString("hdrNoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Cek.
        /// </summary>
        public static string hdrNoCek {
            get {
                return ResourceManager.GetString("hdrNoCek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Dokumen.
        /// </summary>
        public static string hdrNoDkmn {
            get {
                return ResourceManager.GetString("hdrNoDkmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Kontrak / K/P.
        /// </summary>
        public static string hdrNoKntrk {
            get {
                return ResourceManager.GetString("hdrNoKntrk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringkat.
        /// </summary>
        public static string hdrPrgkt {
            get {
                return ResourceManager.GetString("hdrPrgkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENARAI TRANSAKSI CEKROL PEKERJA.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Dokumen.
        /// </summary>
        public static string hdrTrkhDkmn {
            get {
                return ResourceManager.GetString("hdrTrkhDkmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerakyatan.
        /// </summary>
        public static string lblKrkytan {
            get {
                return ResourceManager.GetString("lblKrkytan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Dokumen F-43 (SKB).
        /// </summary>
        public static string lblNoDokumen {
            get {
                return ResourceManager.GetString("lblNoDokumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
