//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResPaysheetByLadang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResPaysheetByLadang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResPaysheetByLadang", typeof(GlobalResPaysheetByLadang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWSP + SOCSO.
        /// </summary>
        public static string hdhKwspSocso {
            get {
                return ResourceManager.GetString("hdhKwspSocso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIT.
        /// </summary>
        public static string hdrCit {
            get {
                return ResourceManager.GetString("hdrCit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zon CIT.
        /// </summary>
        public static string hdrCitZone {
            get {
                return ResourceManager.GetString("hdrCitZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Bank.
        /// </summary>
        public static string hdrGlBank {
            get {
                return ResourceManager.GetString("hdrGlBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWSP.
        /// </summary>
        public static string hdrKwsp {
            get {
                return ResourceManager.GetString("hdrKwsp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lain-Lain.
        /// </summary>
        public static string hdrLain2 {
            get {
                return ResourceManager.GetString("hdrLain2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cekrol Manual.
        /// </summary>
        public static string hdrManual {
            get {
                return ResourceManager.GetString("hdrManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Ladang.
        /// </summary>
        public static string hdrNamaLdg {
            get {
                return ResourceManager.GetString("hdrNamaLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NILAI PECAHAN HANTARAN WANG DIPOHON.
        /// </summary>
        public static string hdrNilaiPecahan {
            get {
                return ResourceManager.GetString("hdrNilaiPecahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akaun No (M2E).
        /// </summary>
        public static string hdrNoAkaun {
            get {
                return ResourceManager.GetString("hdrNoAkaun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Dokumen F-43.
        /// </summary>
        public static string hdrNoDkmn {
            get {
                return ResourceManager.GetString("hdrNoDkmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDP.
        /// </summary>
        public static string hdrPdp {
            get {
                return ResourceManager.GetString("hdrPdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendapatan Bersih.
        /// </summary>
        public static string hdrPndptnBrsh {
            get {
                return ResourceManager.GetString("hdrPndptnBrsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDAPATAN KASAR.
        /// </summary>
        public static string hdrPndptnKasar {
            get {
                return ResourceManager.GetString("hdrPndptnKasar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting Date Sistem.
        /// </summary>
        public static string hdrPostingDate {
            get {
                return ResourceManager.GetString("hdrPostingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POTONGAN.
        /// </summary>
        public static string hdrPtgn {
            get {
                return ResourceManager.GetString("hdrPtgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPORAN PAYSHEET MENGIKUT LADANG.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cekrol RML.
        /// </summary>
        public static string hdrRml {
            get {
                return ResourceManager.GetString("hdrRml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCSO.
        /// </summary>
        public static string hdrSocso {
            get {
                return ResourceManager.GetString("hdrSocso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string hdrTotal {
            get {
                return ResourceManager.GetString("hdrTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila Pilih Bulan, Tahun, Wilayah Dan Ladang..
        /// </summary>
        public static string lbltxt {
            get {
                return ResourceManager.GetString("lbltxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu laporan sedang dicapai....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
