//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResApplicationSupport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResApplicationSupport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResApplicationSupport", typeof(GlobalResApplicationSupport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kembali.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cari.
        /// </summary>
        public static string btnCari {
            get {
                return ResourceManager.GetString("btnCari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carian Pantas.
        /// </summary>
        public static string btnFastSearch {
            get {
                return ResourceManager.GetString("btnFastSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jana File.
        /// </summary>
        public static string btnJanaFile {
            get {
                return ResourceManager.GetString("btnJanaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teruskan.
        /// </summary>
        public static string btnProceed {
            get {
                return ResourceManager.GetString("btnProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PILIH.
        /// </summary>
        public static string btnSelect {
            get {
                return ResourceManager.GetString("btnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutup.
        /// </summary>
        public static string btnTutup {
            get {
                return ResourceManager.GetString("btnTutup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALASAN MASUK.
        /// </summary>
        public static string hdrAlsnMsk {
            get {
                return ResourceManager.GetString("hdrAlsnMsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL..
        /// </summary>
        public static string hdrbil {
            get {
                return ResourceManager.GetString("hdrbil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASA TARIKH DICIPTA.
        /// </summary>
        public static string hdrDateCreated {
            get {
                return ResourceManager.GetString("hdrDateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAWATAN.
        /// </summary>
        public static string hdrJwtn {
            get {
                return ResourceManager.GetString("hdrJwtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO KP / PASSPOT.
        /// </summary>
        public static string hdrKP {
            get {
                return ResourceManager.GetString("hdrKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KERAKYATAN.
        /// </summary>
        public static string hdrKrytn {
            get {
                return ResourceManager.GetString("hdrKrytn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA.
        /// </summary>
        public static string hdrNama {
            get {
                return ResourceManager.GetString("hdrNama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA FILE.
        /// </summary>
        public static string hdrNamaFile {
            get {
                return ResourceManager.GetString("hdrNamaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO PEKERJA.
        /// </summary>
        public static string hdrNoPkj {
            get {
                return ResourceManager.GetString("hdrNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        public static string hdrPasswrd {
            get {
                return ResourceManager.GetString("hdrPasswrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PILIHAN.
        /// </summary>
        public static string hdrSelection {
            get {
                return ResourceManager.GetString("hdrSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAIZ FILE (KB).
        /// </summary>
        public static string hdrSizeFile {
            get {
                return ResourceManager.GetString("hdrSizeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string hdrStatus {
            get {
                return ResourceManager.GetString("hdrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUANG TANDA.
        /// </summary>
        public static string hdrTnda {
            get {
                return ResourceManager.GetString("hdrTnda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARIKH SAMPAI.
        /// </summary>
        public static string hdrTrkhSmpai {
            get {
                return ResourceManager.GetString("hdrTrkhSmpai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USER ID.
        /// </summary>
        public static string hdrUserID {
            get {
                return ResourceManager.GetString("hdrUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carian Pantas.
        /// </summary>
        public static string lblFastSearch {
            get {
                return ResourceManager.GetString("lblFastSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenis Sokongan.
        /// </summary>
        public static string lblJenisSokongan {
            get {
                return ResourceManager.GetString("lblJenisSokongan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadangName {
            get {
                return ResourceManager.GetString("lblLadangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila Pilih Tahun, Wilayah, Ladang Dan Status..
        /// </summary>
        public static string lblSelectionNote {
            get {
                return ResourceManager.GetString("lblSelectionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sokongan.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayahName {
            get {
                return ResourceManager.GetString("lblWilayahName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang dicari....
        /// </summary>
        public static string msgWait {
            get {
                return ResourceManager.GetString("msgWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Ladang.
        /// </summary>
        public static string txtboxCodeLadang {
            get {
                return ResourceManager.GetString("txtboxCodeLadang", resourceCulture);
            }
        }
    }
}
