//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResEstateDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResEstateDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResEstateDetail", typeof(GlobalResEstateDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tambah Data Baru.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kembali.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak.
        /// </summary>
        public static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya.
        /// </summary>
        public static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adakah anda pasti untuk menghapuskan maklumat berikut?.
        /// </summary>
        public static string DeleteMsg {
            get {
                return ResourceManager.GetString("DeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Acc.
        /// </summary>
        public static string hdrAcc {
            get {
                return ResourceManager.GetString("hdrAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tindakan.
        /// </summary>
        public static string hdrAction {
            get {
                return ResourceManager.GetString("hdrAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CIT.
        /// </summary>
        public static string hdrCIT {
            get {
                return ResourceManager.GetString("hdrCIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Ladang.
        /// </summary>
        public static string hdrCode {
            get {
                return ResourceManager.GetString("hdrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Vendor.
        /// </summary>
        public static string hdrCPD {
            get {
                return ResourceManager.GetString("hdrCPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emel Ladang.
        /// </summary>
        public static string hdrEmail {
            get {
                return ResourceManager.GetString("hdrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No GL.
        /// </summary>
        public static string hdrGL {
            get {
                return ResourceManager.GetString("hdrGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Ladang.
        /// </summary>
        public static string hdrName {
            get {
                return ResourceManager.GetString("hdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Syarikat.
        /// </summary>
        public static string hdrSyarikat {
            get {
                return ResourceManager.GetString("hdrSyarikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah ID.
        /// </summary>
        public static string hdrWlyhid {
            get {
                return ResourceManager.GetString("hdrWlyhid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Wilayah.
        /// </summary>
        public static string hdrWlyhName {
            get {
                return ResourceManager.GetString("hdrWlyhName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syarikat.
        /// </summary>
        public static string lblSyarikat {
            get {
                return ResourceManager.GetString("lblSyarikat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penambahan Data Baru.
        /// </summary>
        public static string lblTitleCreate {
            get {
                return ResourceManager.GetString("lblTitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hapus Data.
        /// </summary>
        public static string lblTitleDelete {
            get {
                return ResourceManager.GetString("lblTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kemaskini Data.
        /// </summary>
        public static string lblTitleUpdate {
            get {
                return ResourceManager.GetString("lblTitleUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
    }
}
