//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResWorkerReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResWorkerReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResWorkerReport", typeof(GlobalResWorkerReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviti.
        /// </summary>
        public static string hdrAktiviti {
            get {
                return ResourceManager.GetString("hdrAktiviti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amt/ Unit.
        /// </summary>
        public static string hdrAmt {
            get {
                return ResourceManager.GetString("hdrAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string hdrBil {
            get {
                return ResourceManager.GetString("hdrBil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hujan.
        /// </summary>
        public static string hdrHujan {
            get {
                return ResourceManager.GetString("hdrHujan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Pengguna.
        /// </summary>
        public static string hdrId {
            get {
                return ResourceManager.GetString("hdrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah (RM).
        /// </summary>
        public static string hdrJumlah {
            get {
                return ResourceManager.GetString("hdrJumlah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kadar Lebihan Masa.
        /// </summary>
        public static string hdrKdrLbhMasa {
            get {
                return ResourceManager.GetString("hdrKdrLbhMasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kehadiran.
        /// </summary>
        public static string hdrKehadiran {
            get {
                return ResourceManager.GetString("hdrKehadiran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KGK (%).
        /// </summary>
        public static string hdrKgk {
            get {
                return ResourceManager.GetString("hdrKgk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kong.
        /// </summary>
        public static string hdrKong {
            get {
                return ResourceManager.GetString("hdrKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuantiti.
        /// </summary>
        public static string hdrKuantiti {
            get {
                return ResourceManager.GetString("hdrKuantiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kumpulan.
        /// </summary>
        public static string hdrKumpulan {
            get {
                return ResourceManager.GetString("hdrKumpulan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebih Masa.
        /// </summary>
        public static string hdrLbhMasa {
            get {
                return ResourceManager.GetString("hdrLbhMasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejar.
        /// </summary>
        public static string hdrLejar {
            get {
                return ResourceManager.GetString("hdrLejar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Pengguna.
        /// </summary>
        public static string hdrNama {
            get {
                return ResourceManager.GetString("hdrNama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Kontrak.
        /// </summary>
        public static string hdrNoKontrak {
            get {
                return ResourceManager.GetString("hdrNoKontrak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cara Pengiraan.
        /// </summary>
        public static string hdrPengiraan {
            get {
                return ResourceManager.GetString("hdrPengiraan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringkat.
        /// </summary>
        public static string hdrPeringkat {
            get {
                return ResourceManager.GetString("hdrPeringkat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPORAN MAKLUMAT KERJA.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh.
        /// </summary>
        public static string hdrTarikh {
            get {
                return ResourceManager.GetString("hdrTarikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string hdrTask {
            get {
                return ResourceManager.GetString("hdrTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string hdrUnit {
            get {
                return ResourceManager.GetString("hdrUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pekerja.
        /// </summary>
        public static string lblNoPkj {
            get {
                return ResourceManager.GetString("lblNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
