//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResWorkerSalary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResWorkerSalary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResWorkerSalary", typeof(GlobalResWorkerSalary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM 1,001 - RM 1,500.
        /// </summary>
        public static string hdr10011500 {
            get {
                return ResourceManager.GetString("hdr10011500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM 1,500 KE ATAS.
        /// </summary>
        public static string hdrAts1500 {
            get {
                return ResourceManager.GetString("hdrAts1500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL. PEKERJA.
        /// </summary>
        public static string hdrBilPkjSms {
            get {
                return ResourceManager.GetString("hdrBilPkjSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM 1,000 KE BAWAH.
        /// </summary>
        public static string hdrBwh1000 {
            get {
                return ResourceManager.GetString("hdrBwh1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOD LADANG.
        /// </summary>
        public static string hdrCodeLadang {
            get {
                return ResourceManager.GetString("hdrCodeLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LADANG.
        /// </summary>
        public static string hdrEstate {
            get {
                return ResourceManager.GetString("hdrEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KERAKYATAN.
        /// </summary>
        public static string hdrKrytan {
            get {
                return ResourceManager.GetString("hdrKrytan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA LADANG.
        /// </summary>
        public static string hdrLadangName {
            get {
                return ResourceManager.GetString("hdrLadangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA PEKERJA.
        /// </summary>
        public static string hdrNamePkj {
            get {
                return ResourceManager.GetString("hdrNamePkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. PEKERJA.
        /// </summary>
        public static string hdrNoPkj {
            get {
                return ResourceManager.GetString("hdrNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERENDAH.
        /// </summary>
        public static string hdrPenRndh {
            get {
                return ResourceManager.GetString("hdrPenRndh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERTINGGI.
        /// </summary>
        public static string hdrPenTggi {
            get {
                return ResourceManager.GetString("hdrPenTggi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDAPATAN.
        /// </summary>
        public static string hdrPrtaPen {
            get {
                return ResourceManager.GetString("hdrPrtaPen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPORAN BULANAN PENDAPATAN PEKERJA LADANG.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH.
        /// </summary>
        public static string hdrTotal {
            get {
                return ResourceManager.GetString("hdrTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH KESELURUHAN.
        /// </summary>
        public static string hdrTotalAll {
            get {
                return ResourceManager.GetString("hdrTotalAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerakyatan.
        /// </summary>
        public static string lblKrkytan {
            get {
                return ResourceManager.GetString("lblKrkytan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila Pilih Bulan, Tahun, Wilayah, Ladang Dan Kerakyatan..
        /// </summary>
        public static string lblSelectionNote {
            get {
                return ResourceManager.GetString("lblSelectionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumusan kesuluruhan.
        /// </summary>
        public static string lblSummaryTextAll {
            get {
                return ResourceManager.GetString("lblSummaryTextAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumusan bagi.
        /// </summary>
        public static string lblSummaryTextSelected {
            get {
                return ResourceManager.GetString("lblSummaryTextSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA WILAYAH.
        /// </summary>
        public static string lblWilayahName {
            get {
                return ResourceManager.GetString("lblWilayahName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
