//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResActiveWorker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResActiveWorker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResActiveWorker", typeof(GlobalResActiveWorker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASING.
        /// </summary>
        public static string hdrAsing {
            get {
                return ResourceManager.GetString("hdrAsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL. PEKERJA SEMASA.
        /// </summary>
        public static string hdrBilPkjSms {
            get {
                return ResourceManager.GetString("hdrBilPkjSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOD LADANG.
        /// </summary>
        public static string hdrCodeLadang {
            get {
                return ResourceManager.GetString("hdrCodeLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LADANG.
        /// </summary>
        public static string hdrEstate {
            get {
                return ResourceManager.GetString("hdrEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSP. KUALITI.
        /// </summary>
        public static string hdrInpekKualiti {
            get {
                return ResourceManager.GetString("hdrInpekKualiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEKURANGAN SEMASA (%).
        /// </summary>
        public static string hdrKrngSms {
            get {
                return ResourceManager.GetString("hdrKrngSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA LADANG.
        /// </summary>
        public static string hdrLadangName {
            get {
                return ResourceManager.GetString("hdrLadangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOADER.
        /// </summary>
        public static string hdrLoader {
            get {
                return ResourceManager.GetString("hdrLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNDOR AM.
        /// </summary>
        public static string hdrMndrAM {
            get {
                return ResourceManager.GetString("hdrMndrAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NISBAH / PEKERJA / HA.
        /// </summary>
        public static string hdrNisbah {
            get {
                return ResourceManager.GetString("hdrNisbah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAIN-LAIN.
        /// </summary>
        public static string hdrother {
            get {
                return ResourceManager.GetString("hdrother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMNDU.
        /// </summary>
        public static string hdrPemandu {
            get {
                return ResourceManager.GetString("hdrPemandu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNOREH.
        /// </summary>
        public static string hdrPenoreh {
            get {
                return ResourceManager.GetString("hdrPenoreh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENUAI.
        /// </summary>
        public static string hdrPenuai {
            get {
                return ResourceManager.GetString("hdrPenuai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERLU.
        /// </summary>
        public static string hdrPerlu {
            get {
                return ResourceManager.GetString("hdrPerlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAKI PERLU.
        /// </summary>
        public static string hdrPerluSemasa {
            get {
                return ResourceManager.GetString("hdrPerluSemasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PKJ AM.
        /// </summary>
        public static string hdrPkjAm {
            get {
                return ResourceManager.GetString("hdrPkjAm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA PROJEK.
        /// </summary>
        public static string hdrProjectName {
            get {
                return ResourceManager.GetString("hdrProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BILANGAN PROJEK.
        /// </summary>
        public static string hdrProjectTotal {
            get {
                return ResourceManager.GetString("hdrProjectTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUMUSAN KEDUDUKAN &amp; KEPERLUAN PEKERJA LADANG.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMAI.
        /// </summary>
        public static string hdrSemaian {
            get {
                return ResourceManager.GetString("hdrSemaian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak Aktif.
        /// </summary>
        public static string hdrStatus0 {
            get {
                return ResourceManager.GetString("hdrStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string hdrStatus1 {
            get {
                return ResourceManager.GetString("hdrStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Dan Tidak Aktif.
        /// </summary>
        public static string hdrStatus2 {
            get {
                return ResourceManager.GetString("hdrStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKB.
        /// </summary>
        public static string hdrTKB {
            get {
                return ResourceManager.GetString("hdrTKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKI.
        /// </summary>
        public static string hdrTKI {
            get {
                return ResourceManager.GetString("hdrTKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKIN.
        /// </summary>
        public static string hdrTKIN {
            get {
                return ResourceManager.GetString("hdrTKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKK.
        /// </summary>
        public static string hdrTKK {
            get {
                return ResourceManager.GetString("hdrTKK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKN.
        /// </summary>
        public static string hdrTKN {
            get {
                return ResourceManager.GetString("hdrTKN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKP.
        /// </summary>
        public static string hdrTKP {
            get {
                return ResourceManager.GetString("hdrTKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKPH.
        /// </summary>
        public static string hdrTKPH {
            get {
                return ResourceManager.GetString("hdrTKPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKT.
        /// </summary>
        public static string hdrTKT {
            get {
                return ResourceManager.GetString("hdrTKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKTH.
        /// </summary>
        public static string hdrTKTH {
            get {
                return ResourceManager.GetString("hdrTKTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TKV.
        /// </summary>
        public static string hdrTKV {
            get {
                return ResourceManager.GetString("hdrTKV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH.
        /// </summary>
        public static string hdrTotal {
            get {
                return ResourceManager.GetString("hdrTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH KESELURUHAN.
        /// </summary>
        public static string hdrTotalAll {
            get {
                return ResourceManager.GetString("hdrTotalAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LUAS (HA).
        /// </summary>
        public static string hdrWide {
            get {
                return ResourceManager.GetString("hdrWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPSI.
        /// </summary>
        public static string hrdOps {
            get {
                return ResourceManager.GetString("hrdOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerakyatan.
        /// </summary>
        public static string lblKrkytan {
            get {
                return ResourceManager.GetString("lblKrkytan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila Pilih Tahun, Wilayah, Ladang Dan Status..
        /// </summary>
        public static string lblSelectionNote {
            get {
                return ResourceManager.GetString("lblSelectionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH DATA DIMUAT NAIK.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH LADANG.
        /// </summary>
        public static string lblTotalLadang {
            get {
                return ResourceManager.GetString("lblTotalLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA WILAYAH.
        /// </summary>
        public static string lblWilayahName {
            get {
                return ResourceManager.GetString("lblWilayahName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTIF.
        /// </summary>
        public static string sltActive {
            get {
                return ResourceManager.GetString("sltActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIDAK AKTIF.
        /// </summary>
        public static string sltNotActive {
            get {
                return ResourceManager.GetString("sltNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
