//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResWorkerTransacSalary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResWorkerTransacSalary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResWorkerTransacSalary", typeof(GlobalResWorkerTransacSalary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH.
        /// </summary>
        public static string ftrJumlah {
            get {
                return ResourceManager.GetString("ftrJumlah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaji Buruh (RM).
        /// </summary>
        public static string hdrGajiBuruh {
            get {
                return ResourceManager.GetString("hdrGajiBuruh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Ladang.
        /// </summary>
        public static string hdrKodLdg {
            get {
                return ResourceManager.GetString("hdrKodLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Ladang.
        /// </summary>
        public static string hdrNamaLdg {
            get {
                return ResourceManager.GetString("hdrNamaLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMOHONAN GAJI BURUH.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila Pilih Bulan, Tahun, Wilayah Dan Ladang.
        /// </summary>
        public static string lblText {
            get {
                return ResourceManager.GetString("lblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
