//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResPermitPassportPopup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResPermitPassportPopup() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResPermitPassportPopup", typeof(GlobalResPermitPassportPopup).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL. BULAN TAMAT.
        /// </summary>
        public static string fld_BilBlnTmtPrmnt {
            get {
                return ResourceManager.GetString("fld_BilBlnTmtPrmnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL. BULAN TAMAT.
        /// </summary>
        public static string fld_BilBlnTmtPsprt {
            get {
                return ResourceManager.GetString("fld_BilBlnTmtPsprt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA.
        /// </summary>
        public static string fld_Nama1 {
            get {
                return ResourceManager.GetString("fld_Nama1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. PASPORT.
        /// </summary>
        public static string fld_Nokp {
            get {
                return ResourceManager.GetString("fld_Nokp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. PEKERJA.
        /// </summary>
        public static string fld_Nopkj {
            get {
                return ResourceManager.GetString("fld_Nopkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. PERMIT.
        /// </summary>
        public static string fld_Prmtno {
            get {
                return ResourceManager.GetString("fld_Prmtno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARIKH T. PERMIT.
        /// </summary>
        public static string fld_T2prmt {
            get {
                return ResourceManager.GetString("fld_T2prmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARIKH T. PASPORT.
        /// </summary>
        public static string fld_Ttsplp {
            get {
                return ResourceManager.GetString("fld_Ttsplp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama File.
        /// </summary>
        public static string hdrNamaFile {
            get {
                return ResourceManager.GetString("hdrNamaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string hdrStatus {
            get {
                return ResourceManager.GetString("hdrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Permohonan.
        /// </summary>
        public static string hdrTrkhMohon {
            get {
                return ResourceManager.GetString("hdrTrkhMohon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passpot.
        /// </summary>
        public static string lblJvPassport {
            get {
                return ResourceManager.GetString("lblJvPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit.
        /// </summary>
        public static string lblJvPermit {
            get {
                return ResourceManager.GetString("lblJvPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelulusan ID Pengguna Baru.
        /// </summary>
        public static string lblJvUserIDApp {
            get {
                return ResourceManager.GetString("lblJvUserIDApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelulusan Pekerja Baru.
        /// </summary>
        public static string lblJvWorkerApp {
            get {
                return ResourceManager.GetString("lblJvWorkerApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LADANG.
        /// </summary>
        public static string lblLadangName {
            get {
                return ResourceManager.GetString("lblLadangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH PEKERJA.
        /// </summary>
        public static string lblTotalStaff {
            get {
                return ResourceManager.GetString("lblTotalStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA WILAYAH.
        /// </summary>
        public static string lblWilayahName {
            get {
                return ResourceManager.GetString("lblWilayahName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL..
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringatan Tamat Pasport.
        /// </summary>
        public static string PassportReminder {
            get {
                return ResourceManager.GetString("PassportReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORANG.
        /// </summary>
        public static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringatan Tamat Permit.
        /// </summary>
        public static string PermitReminder {
            get {
                return ResourceManager.GetString("PermitReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringatan.
        /// </summary>
        public static string Remainder {
            get {
                return ResourceManager.GetString("Remainder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelulusan Kenaikan Gaji Pekerja.
        /// </summary>
        public static string TaskSalaryIncmntAppReminder {
            get {
                return ResourceManager.GetString("TaskSalaryIncmntAppReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelulusan ID Pengguna Baru.
        /// </summary>
        public static string TaskUserIDAppReminder {
            get {
                return ResourceManager.GetString("TaskUserIDAppReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelulusan Pekerja Baru.
        /// </summary>
        public static string TaskWorkerAppReminder {
            get {
                return ResourceManager.GetString("TaskWorkerAppReminder", resourceCulture);
            }
        }
    }
}
