//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResAuditTrail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResAuditTrail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResAuditTrail", typeof(GlobalResAuditTrail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOD LADANG.
        /// </summary>
        public static string hdrCodeLadang {
            get {
                return ResourceManager.GetString("hdrCodeLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA LADANG.
        /// </summary>
        public static string hdrLadangName {
            get {
                return ResourceManager.GetString("hdrLadangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JANUARI.
        /// </summary>
        public static string hdrM1 {
            get {
                return ResourceManager.GetString("hdrM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKTOBER.
        /// </summary>
        public static string hdrM10 {
            get {
                return ResourceManager.GetString("hdrM10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOVEMBER.
        /// </summary>
        public static string hdrM11 {
            get {
                return ResourceManager.GetString("hdrM11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISEMBER.
        /// </summary>
        public static string hdrM12 {
            get {
                return ResourceManager.GetString("hdrM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEBRUARI.
        /// </summary>
        public static string hdrM2 {
            get {
                return ResourceManager.GetString("hdrM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC.
        /// </summary>
        public static string hdrM3 {
            get {
                return ResourceManager.GetString("hdrM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRIL.
        /// </summary>
        public static string hdrM4 {
            get {
                return ResourceManager.GetString("hdrM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEI.
        /// </summary>
        public static string hdrM5 {
            get {
                return ResourceManager.GetString("hdrM5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUN.
        /// </summary>
        public static string hdrM6 {
            get {
                return ResourceManager.GetString("hdrM6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JULAI.
        /// </summary>
        public static string hdrM7 {
            get {
                return ResourceManager.GetString("hdrM7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OGOS.
        /// </summary>
        public static string hdrM8 {
            get {
                return ResourceManager.GetString("hdrM8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEPTEMBER.
        /// </summary>
        public static string hdrM9 {
            get {
                return ResourceManager.GetString("hdrM9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masa Terakhir Dimuat naik.
        /// </summary>
        public static string lblLastUpload {
            get {
                return ResourceManager.GetString("lblLastUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiada Data.
        /// </summary>
        public static string lblNoData {
            get {
                return ResourceManager.GetString("lblNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH DATA DIMUAT NAIK.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH LADANG.
        /// </summary>
        public static string lblTotalLadang {
            get {
                return ResourceManager.GetString("lblTotalLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA WILAYAH.
        /// </summary>
        public static string lblWilayahName {
            get {
                return ResourceManager.GetString("lblWilayahName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RUMUSAN KESELURUHAN.
        /// </summary>
        public static string sltConclusion {
            get {
                return ResourceManager.GetString("sltConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
