//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResWorkerList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResWorkerList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResWorkerList", typeof(GlobalResWorkerList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat .
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keaktifan.
        /// </summary>
        public static string hdrKeaktifan {
            get {
                return ResourceManager.GetString("hdrKeaktifan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Ladang.
        /// </summary>
        public static string hdrKodLdg {
            get {
                return ResourceManager.GetString("hdrKodLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No KP/ Passport.
        /// </summary>
        public static string hdrKP {
            get {
                return ResourceManager.GetString("hdrKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Ladang.
        /// </summary>
        public static string hdrNamaLdg {
            get {
                return ResourceManager.GetString("hdrNamaLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Pekerja .
        /// </summary>
        public static string hdrNamaPkj {
            get {
                return ResourceManager.GetString("hdrNamaPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pekerja.
        /// </summary>
        public static string hdrNoPkj {
            get {
                return ResourceManager.GetString("hdrNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Tamat Passport.
        /// </summary>
        public static string hdrPassportExprdDate {
            get {
                return ResourceManager.GetString("hdrPassportExprdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Pembekal.
        /// </summary>
        public static string hdrPembekal {
            get {
                return ResourceManager.GetString("hdrPembekal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Tamat Permit.
        /// </summary>
        public static string hdrPermitExprdDate {
            get {
                return ResourceManager.GetString("hdrPermitExprdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENARAI PEKERJA MENGIKUT NAMA ATAU NO KP/ PASSPORT.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebab Tak Aktif.
        /// </summary>
        public static string hdrSbbTkAktf {
            get {
                return ResourceManager.GetString("hdrSbbTkAktf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Mula Khidmat.
        /// </summary>
        public static string hdrTrkhKrja {
            get {
                return ResourceManager.GetString("hdrTrkhKrja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warganegara.
        /// </summary>
        public static string hdrWarganegara {
            get {
                return ResourceManager.GetString("hdrWarganegara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keaktifan.
        /// </summary>
        public static string lblKeaktifan {
            get {
                return ResourceManager.GetString("lblKeaktifan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLdg {
            get {
                return ResourceManager.GetString("lblLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pekerja.
        /// </summary>
        public static string lblNoPkj {
            get {
                return ResourceManager.GetString("lblNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
    }
}
