//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResNewWorkerApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResNewWorkerApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResNewWorkerApp", typeof(GlobalResNewWorkerApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiviti.
        /// </summary>
        public static string hdrAktvt {
            get {
                return ResourceManager.GetString("hdrAktvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diluluskan Oleh.
        /// </summary>
        public static string hdrApprvBy {
            get {
                return ResourceManager.GetString("hdrApprvBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string hdrBil {
            get {
                return ResourceManager.GetString("hdrBil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catatan.
        /// </summary>
        public static string hdrCatatan {
            get {
                return ResourceManager.GetString("hdrCatatan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo1 {
            get {
                return ResourceManager.GetString("hdrCmpnyNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit (RM).
        /// </summary>
        public static string hdrDbt {
            get {
                return ResourceManager.GetString("hdrDbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. P2/P3/Invois.
        /// </summary>
        public static string hdrInvois {
            get {
                return ResourceManager.GetString("hdrInvois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jenis Pekerjaan.
        /// </summary>
        public static string hdrJnsPkrjaan {
            get {
                return ResourceManager.GetString("hdrJnsPkrjaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keterangan.
        /// </summary>
        public static string hdrKeterangan {
            get {
                return ResourceManager.GetString("hdrKeterangan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod Stok.
        /// </summary>
        public static string hdrKodStok {
            get {
                return ResourceManager.GetString("hdrKodStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No KP/ Passport.
        /// </summary>
        public static string hdrKP {
            get {
                return ResourceManager.GetString("hdrKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredit (RM).
        /// </summary>
        public static string hdrKrdt {
            get {
                return ResourceManager.GetString("hdrKrdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keterangan Aktiviti.
        /// </summary>
        public static string hdrKtrgn {
            get {
                return ResourceManager.GetString("hdrKtrgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kuantiti.
        /// </summary>
        public static string hdrKuantiti {
            get {
                return ResourceManager.GetString("hdrKuantiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lejar.
        /// </summary>
        public static string hdrLejar {
            get {
                return ResourceManager.GetString("hdrLejar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama.
        /// </summary>
        public static string hdrNama {
            get {
                return ResourceManager.GetString("hdrNama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Fail.
        /// </summary>
        public static string hdrNamaFail {
            get {
                return ResourceManager.GetString("hdrNamaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoA / Tetap Kend..
        /// </summary>
        public static string hdrNoA {
            get {
                return ResourceManager.GetString("hdrNoA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Cek.
        /// </summary>
        public static string hdrNoCek {
            get {
                return ResourceManager.GetString("hdrNoCek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Dokumen.
        /// </summary>
        public static string hdrNoDkmn {
            get {
                return ResourceManager.GetString("hdrNoDkmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Kontrak / K/P.
        /// </summary>
        public static string hdrNoKntrk {
            get {
                return ResourceManager.GetString("hdrNoKntrk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pekerja.
        /// </summary>
        public static string hdrNoPekerja {
            get {
                return ResourceManager.GetString("hdrNoPekerja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peringkat.
        /// </summary>
        public static string hdrPrgkt {
            get {
                return ResourceManager.GetString("hdrPrgkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENARAI PERMOHONAN PEKERJA BARU.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebab Kemasukan.
        /// </summary>
        public static string hdrSbbKemasukan {
            get {
                return ResourceManager.GetString("hdrSbbKemasukan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Permohonan.
        /// </summary>
        public static string hdrStatus {
            get {
                return ResourceManager.GetString("hdrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Kelulusan.
        /// </summary>
        public static string hdrTarikhKelulusan {
            get {
                return ResourceManager.GetString("hdrTarikhKelulusan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Dokumen.
        /// </summary>
        public static string hdrTrkhDkmn {
            get {
                return ResourceManager.GetString("hdrTrkhDkmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Sampai KLIA/ Tarikh Lantikan.
        /// </summary>
        public static string hdrTrkhLantikan {
            get {
                return ResourceManager.GetString("hdrTrkhLantikan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarikh Permohonan Ke HQ.
        /// </summary>
        public static string hdrTrkhPermohonan {
            get {
                return ResourceManager.GetString("hdrTrkhPermohonan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warganegara.
        /// </summary>
        public static string hdrWarganegara {
            get {
                return ResourceManager.GetString("hdrWarganegara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerakyatan.
        /// </summary>
        public static string lblKrkytan {
            get {
                return ResourceManager.GetString("lblKrkytan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang1 {
            get {
                return ResourceManager.GetString("lblLadang1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth1 {
            get {
                return ResourceManager.GetString("lblMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah1 {
            get {
                return ResourceManager.GetString("lblWilayah1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear1 {
            get {
                return ResourceManager.GetString("lblYear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
