//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResGeneral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResGeneral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResGeneral", typeof(GlobalResGeneral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahad.
        /// </summary>
        public static string hdrD1 {
            get {
                return ResourceManager.GetString("hdrD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isnin.
        /// </summary>
        public static string hdrD2 {
            get {
                return ResourceManager.GetString("hdrD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selasa.
        /// </summary>
        public static string hdrD3 {
            get {
                return ResourceManager.GetString("hdrD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabu.
        /// </summary>
        public static string hdrD4 {
            get {
                return ResourceManager.GetString("hdrD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khamis.
        /// </summary>
        public static string hdrD5 {
            get {
                return ResourceManager.GetString("hdrD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumaat.
        /// </summary>
        public static string hdrD6 {
            get {
                return ResourceManager.GetString("hdrD6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabtu.
        /// </summary>
        public static string hdrD7 {
            get {
                return ResourceManager.GetString("hdrD7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januari.
        /// </summary>
        public static string hdrM1 {
            get {
                return ResourceManager.GetString("hdrM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktober.
        /// </summary>
        public static string hdrM10 {
            get {
                return ResourceManager.GetString("hdrM10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string hdrM11 {
            get {
                return ResourceManager.GetString("hdrM11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disember.
        /// </summary>
        public static string hdrM12 {
            get {
                return ResourceManager.GetString("hdrM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februari.
        /// </summary>
        public static string hdrM2 {
            get {
                return ResourceManager.GetString("hdrM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac.
        /// </summary>
        public static string hdrM3 {
            get {
                return ResourceManager.GetString("hdrM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string hdrM4 {
            get {
                return ResourceManager.GetString("hdrM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mei.
        /// </summary>
        public static string hdrM5 {
            get {
                return ResourceManager.GetString("hdrM5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string hdrM6 {
            get {
                return ResourceManager.GetString("hdrM6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julai.
        /// </summary>
        public static string hdrM7 {
            get {
                return ResourceManager.GetString("hdrM7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogos.
        /// </summary>
        public static string hdrM8 {
            get {
                return ResourceManager.GetString("hdrM8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string hdrM9 {
            get {
                return ResourceManager.GetString("hdrM9", resourceCulture);
            }
        }
    }
}
