//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResCompanyDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResCompanyDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResCompanyDetail", typeof(GlobalResCompanyDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kembali.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpan.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kemaskini.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Syarikat.
        /// </summary>
        public static string lblCompany {
            get {
                return ResourceManager.GetString("lblCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emel Syarikat.
        /// </summary>
        public static string lblCompanyEmail {
            get {
                return ResourceManager.GetString("lblCompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singkatan Nama Syarikat.
        /// </summary>
        public static string lblCompanyNickname {
            get {
                return ResourceManager.GetString("lblCompanyNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string lblCompanyNo {
            get {
                return ResourceManager.GetString("lblCompanyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maklumat Syarikat.
        /// </summary>
        public static string lblTitleCompany {
            get {
                return ResourceManager.GetString("lblTitleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kemaskini Data.
        /// </summary>
        public static string lblTitleUpdate {
            get {
                return ResourceManager.GetString("lblTitleUpdate", resourceCulture);
            }
        }
    }
}
