//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResLocalWorkerInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResLocalWorkerInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResLocalWorkerInfo", typeof(GlobalResLocalWorkerInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMUR.
        /// </summary>
        public static string hdrAge {
            get {
                return ResourceManager.GetString("hdrAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOD LADANG.
        /// </summary>
        public static string hdrCodeLadang {
            get {
                return ResourceManager.GetString("hdrCodeLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LADANG.
        /// </summary>
        public static string hdrEstate {
            get {
                return ResourceManager.GetString("hdrEstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA LADANG.
        /// </summary>
        public static string hdrLadangName {
            get {
                return ResourceManager.GetString("hdrLadangName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string hdrNA {
            get {
                return ResourceManager.GetString("hdrNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIL..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAKLUMAT PEKERJA TEMPATAN (UMUR).
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPOH KHIDMAT.
        /// </summary>
        public static string hdrSrvce {
            get {
                return ResourceManager.GetString("hdrSrvce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidak Aktif.
        /// </summary>
        public static string hdrStatus0 {
            get {
                return ResourceManager.GetString("hdrStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif.
        /// </summary>
        public static string hdrStatus1 {
            get {
                return ResourceManager.GetString("hdrStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH.
        /// </summary>
        public static string hdrTotal {
            get {
                return ResourceManager.GetString("hdrTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH KESELURUHAN.
        /// </summary>
        public static string hdrTotalAll {
            get {
                return ResourceManager.GetString("hdrTotalAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH PEKERJA.
        /// </summary>
        public static string hdrTtlWrker {
            get {
                return ResourceManager.GetString("hdrTtlWrker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA WILAYAH.
        /// </summary>
        public static string hdrWilayahName {
            get {
                return ResourceManager.GetString("hdrWilayahName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAMA PEKERJA.
        /// </summary>
        public static string hdrWkerName {
            get {
                return ResourceManager.GetString("hdrWkerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. IC PEKERJA.
        /// </summary>
        public static string hdrWrkerIDNo {
            get {
                return ResourceManager.GetString("hdrWrkerIDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO. PEKERJA.
        /// </summary>
        public static string hdrWrkerNo {
            get {
                return ResourceManager.GetString("hdrWrkerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLadang {
            get {
                return ResourceManager.GetString("lblLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila Pilih Tahun, Wilayah, Ladang Dan Status..
        /// </summary>
        public static string lblSelectionNote {
            get {
                return ResourceManager.GetString("lblSelectionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH DATA DIMUAT NAIK.
        /// </summary>
        public static string lblTotal {
            get {
                return ResourceManager.GetString("lblTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUMLAH LADANG.
        /// </summary>
        public static string lblTotalLadang {
            get {
                return ResourceManager.GetString("lblTotalLadang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahun.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKTIF.
        /// </summary>
        public static string sltActive {
            get {
                return ResourceManager.GetString("sltActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIDAK AKTIF.
        /// </summary>
        public static string sltNotActive {
            get {
                return ResourceManager.GetString("sltNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
