//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResPaysheet {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResPaysheet() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResPaysheet", typeof(GlobalResPaysheet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil..
        /// </summary>
        public static string hdrBil {
            get {
                return ResourceManager.GetString("hdrBil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaji Kasar (RM).
        /// </summary>
        public static string hdrGajiKasar {
            get {
                return ResourceManager.GetString("hdrGajiKasar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Bersih (RM).
        /// </summary>
        public static string hdrJumlahBrsih {
            get {
                return ResourceManager.GetString("hdrJumlahBrsih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Pendapatan + Sumbangan (RM).
        /// </summary>
        public static string hdrJumlahPndptnSmbgn {
            get {
                return ResourceManager.GetString("hdrJumlahPndptnSmbgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jumlah Potongan (RM).
        /// </summary>
        public static string hdrJumlahPtgn {
            get {
                return ResourceManager.GetString("hdrJumlahPtgn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWSP (Majikan) (RM).
        /// </summary>
        public static string hdrKwspMajikan {
            get {
                return ResourceManager.GetString("hdrKwspMajikan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KWSP Majikan + Pekerja (RM).
        /// </summary>
        public static string hdrKwspMajikanPkj {
            get {
                return ResourceManager.GetString("hdrKwspMajikanPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nama Pekerja.
        /// </summary>
        public static string hdrNamaPkj {
            get {
                return ResourceManager.GetString("hdrNamaPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Akaun Bank.
        /// </summary>
        public static string hdrNoAkaun {
            get {
                return ResourceManager.GetString("hdrNoAkaun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Kad Pengenalan/ No Passport Pekerja Asing.
        /// </summary>
        public static string hdrNoKP {
            get {
                return ResourceManager.GetString("hdrNoKP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pekerja.
        /// </summary>
        public static string hdrNoPkj {
            get {
                return ResourceManager.GetString("hdrNoPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PENDAPATAN.
        /// </summary>
        public static string hdrPendapatan {
            get {
                return ResourceManager.GetString("hdrPendapatan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendapatan Lain-Lain (RM).
        /// </summary>
        public static string hdrPendapatanLain {
            get {
                return ResourceManager.GetString("hdrPendapatanLain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POTONGAN.
        /// </summary>
        public static string hdrPotongan {
            get {
                return ResourceManager.GetString("hdrPotongan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potongan Lain-Lain (RM).
        /// </summary>
        public static string hdrPotonganLain {
            get {
                return ResourceManager.GetString("hdrPotonganLain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPORAN PAYSHEET.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCSO (Majikan) (RM).
        /// </summary>
        public static string hdrSocsoMajikan {
            get {
                return ResourceManager.GetString("hdrSocsoMajikan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCSO Majikan + Pekerja (RM).
        /// </summary>
        public static string HdrSocsoMajikanPkj {
            get {
                return ResourceManager.GetString("HdrSocsoMajikanPkj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMBANGAN.
        /// </summary>
        public static string hdrSumbangan {
            get {
                return ResourceManager.GetString("hdrSumbangan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tandatangan Pekerja.
        /// </summary>
        public static string hdrTtPkj {
            get {
                return ResourceManager.GetString("hdrTtPkj", resourceCulture);
            }
        }
    }
}
