//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResWorkerMyeg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResWorkerMyeg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResWorkerMyeg", typeof(GlobalResWorkerMyeg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat.
        /// </summary>
        public static string btnViewName {
            get {
                return ResourceManager.GetString("btnViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string ftrTotal {
            get {
                return ResourceManager.GetString("ftrTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANK GUARANTEE NO.
        /// </summary>
        public static string hdrBank {
            get {
                return ResourceManager.GetString("hdrBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMIT EXPIRED MONTH.
        /// </summary>
        public static string hdrBilPrmtExprdDate {
            get {
                return ResourceManager.GetString("hdrBilPrmtExprdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSPORT EXPIRED MONTH.
        /// </summary>
        public static string hdrBilPsptExprdDate {
            get {
                return ResourceManager.GetString("hdrBilPsptExprdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Syarikat.
        /// </summary>
        public static string hdrCmpnyNo {
            get {
                return ResourceManager.GetString("hdrCmpnyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENDER.
        /// </summary>
        public static string hdrJantina {
            get {
                return ResourceManager.GetString("hdrJantina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATIONALITY.
        /// </summary>
        public static string hdrKrytn {
            get {
                return ResourceManager.GetString("hdrKrytn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string hdrKrytn2 {
            get {
                return ResourceManager.GetString("hdrKrytn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJEK.
        /// </summary>
        public static string hdrLdg {
            get {
                return ResourceManager.GetString("hdrLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FW NAME.
        /// </summary>
        public static string hdrName {
            get {
                return ResourceManager.GetString("hdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW PASSPORT NO.
        /// </summary>
        public static string hdrNewPspt {
            get {
                return ResourceManager.GetString("hdrNewPspt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil..
        /// </summary>
        public static string hdrNo {
            get {
                return ResourceManager.GetString("hdrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO CHECK.
        /// </summary>
        public static string hdrNoCheck {
            get {
                return ResourceManager.GetString("hdrNoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD PASSPORT NO.
        /// </summary>
        public static string hdrOldPspt {
            get {
                return ResourceManager.GetString("hdrOldPspt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge (RM).
        /// </summary>
        public static string hdrPrice {
            get {
                return ResourceManager.GetString("hdrPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERMIT EXPIRY DATE.
        /// </summary>
        public static string hdrPrmtExprd {
            get {
                return ResourceManager.GetString("hdrPrmtExprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSPORT DATE OF ISSUE.
        /// </summary>
        public static string hdrPsptDate {
            get {
                return ResourceManager.GetString("hdrPsptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSPORT EXPIRY DATE.
        /// </summary>
        public static string hdrPsptExprd {
            get {
                return ResourceManager.GetString("hdrPsptExprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENARAI MAKLUMAT PEKERJA.
        /// </summary>
        public static string hdrReportTitle {
            get {
                return ResourceManager.GetString("hdrReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROC PERMIT.
        /// </summary>
        public static string hdrRocPrmt {
            get {
                return ResourceManager.GetString("hdrRocPrmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REF. NO.
        /// </summary>
        public static string hdrRujukan {
            get {
                return ResourceManager.GetString("hdrRujukan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO RUJUKAN SPPA.
        /// </summary>
        public static string hdrRujukanSPPA {
            get {
                return ResourceManager.GetString("hdrRujukanSPPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY.
        /// </summary>
        public static string hdrRumusan {
            get {
                return ResourceManager.GetString("hdrRumusan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIAL PASS (SP) EXPIRY DATE.
        /// </summary>
        public static string hdrSpExprd {
            get {
                return ResourceManager.GetString("hdrSpExprd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLD STICKER NUMBER.
        /// </summary>
        public static string hdrSticker {
            get {
                return ResourceManager.GetString("hdrSticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAR.
        /// </summary>
        public static string hdrTahun {
            get {
                return ResourceManager.GetString("hdrTahun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARIKH EMEL KE MYEG.
        /// </summary>
        public static string hdrTemel {
            get {
                return ResourceManager.GetString("hdrTemel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF BIRTH.
        /// </summary>
        public static string hdrTlahir {
            get {
                return ResourceManager.GetString("hdrTlahir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Charge (RM).
        /// </summary>
        public static string hdrTotalSalary {
            get {
                return ResourceManager.GetString("hdrTotalSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        public static string hdrWorker {
            get {
                return ResourceManager.GetString("hdrWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKER TYPE.
        /// </summary>
        public static string hdrWorkerType {
            get {
                return ResourceManager.GetString("hdrWorkerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulan Tamat Passport.
        /// </summary>
        public static string lblBulan {
            get {
                return ResourceManager.GetString("lblBulan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerakyatan.
        /// </summary>
        public static string lblKrytn {
            get {
                return ResourceManager.GetString("lblKrytn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladang.
        /// </summary>
        public static string lblLdg {
            get {
                return ResourceManager.GetString("lblLdg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilayah.
        /// </summary>
        public static string lblWilayah {
            get {
                return ResourceManager.GetString("lblWilayah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu data sedang diproses....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
