//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_SYSTEM.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_SYSTEM.App_LocalResources.GlobalResReport", typeof(GlobalResReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lihat Laporan.
        /// </summary>
        public static string btnViewReport {
            get {
                return ResourceManager.GetString("btnViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senarai Laporan.
        /// </summary>
        public static string lblReportList {
            get {
                return ResourceManager.GetString("lblReportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laporan.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string sltActive {
            get {
                return ResourceManager.GetString("sltActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEMUA.
        /// </summary>
        public static string sltAll {
            get {
                return ResourceManager.GetString("sltAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT ACTIVE.
        /// </summary>
        public static string sltNotActive {
            get {
                return ResourceManager.GetString("sltNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sila tunggu laporan sedang dicapai....
        /// </summary>
        public static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
    }
}
