//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SysXml = System.Xml;
namespace MVC_SYSTEM.SAPMD_FLP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", ConfigurationName="SAPMD_FLP.ZWS_OPMS_MASTER")]
    public interface ZWS_OPMS_MASTER {
        
        // CODEGEN: Generating message contract since the operation ZfmOpmsMaster is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse1 ZfmOpmsMaster(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse1> ZfmOpmsMasterAsync(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmOpmsMaster : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ccBeginField;
        
        private string ccCompField;
        
        private string ccEndField;
        
        private string csBeginField;
        
        private string csCompField;
        
        private string csEndField;
        
        private string dateBeginField;
        
        private string dateEndField;
        
        private string glBeginField;
        
        private string glCompField;
        
        private string glEndField;
        
        private Zopmscc[] itCcField;
        
        private Zopmscs[] itCustField;
        
        private Zopmsgl[] itGlField;
        
        private Zopmsslp[] itSlpField;
        
        private Zopmsvd[] itVendField;
        
        private string slpCompField;
        
        private string slpIndBeginField;
        
        private string slpIndEndField;
        
        private string slpPktBeginField;
        
        private string slpPktEndField;
        
        private string slpRanBeginField;
        
        private string slpRanEndField;
        
        private string vdBeginField;
        
        private string vdCompField;
        
        private string vdEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CcBegin {
            get {
                return this.ccBeginField;
            }
            set {
                this.ccBeginField = value;
                this.RaisePropertyChanged("CcBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CcComp {
            get {
                return this.ccCompField;
            }
            set {
                this.ccCompField = value;
                this.RaisePropertyChanged("CcComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CcEnd {
            get {
                return this.ccEndField;
            }
            set {
                this.ccEndField = value;
                this.RaisePropertyChanged("CcEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CsBegin {
            get {
                return this.csBeginField;
            }
            set {
                this.csBeginField = value;
                this.RaisePropertyChanged("CsBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string CsComp {
            get {
                return this.csCompField;
            }
            set {
                this.csCompField = value;
                this.RaisePropertyChanged("CsComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string CsEnd {
            get {
                return this.csEndField;
            }
            set {
                this.csEndField = value;
                this.RaisePropertyChanged("CsEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DateBegin {
            get {
                return this.dateBeginField;
            }
            set {
                this.dateBeginField = value;
                this.RaisePropertyChanged("DateBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
                this.RaisePropertyChanged("DateEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string GlBegin {
            get {
                return this.glBeginField;
            }
            set {
                this.glBeginField = value;
                this.RaisePropertyChanged("GlBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string GlComp {
            get {
                return this.glCompField;
            }
            set {
                this.glCompField = value;
                this.RaisePropertyChanged("GlComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string GlEnd {
            get {
                return this.glEndField;
            }
            set {
                this.glEndField = value;
                this.RaisePropertyChanged("GlEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmscc[] ItCc {
            get {
                return this.itCcField;
            }
            set {
                this.itCcField = value;
                this.RaisePropertyChanged("ItCc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmscs[] ItCust {
            get {
                return this.itCustField;
            }
            set {
                this.itCustField = value;
                this.RaisePropertyChanged("ItCust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmsgl[] ItGl {
            get {
                return this.itGlField;
            }
            set {
                this.itGlField = value;
                this.RaisePropertyChanged("ItGl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmsslp[] ItSlp {
            get {
                return this.itSlpField;
            }
            set {
                this.itSlpField = value;
                this.RaisePropertyChanged("ItSlp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmsvd[] ItVend {
            get {
                return this.itVendField;
            }
            set {
                this.itVendField = value;
                this.RaisePropertyChanged("ItVend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string SlpComp {
            get {
                return this.slpCompField;
            }
            set {
                this.slpCompField = value;
                this.RaisePropertyChanged("SlpComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string SlpIndBegin {
            get {
                return this.slpIndBeginField;
            }
            set {
                this.slpIndBeginField = value;
                this.RaisePropertyChanged("SlpIndBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string SlpIndEnd {
            get {
                return this.slpIndEndField;
            }
            set {
                this.slpIndEndField = value;
                this.RaisePropertyChanged("SlpIndEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string SlpPktBegin {
            get {
                return this.slpPktBeginField;
            }
            set {
                this.slpPktBeginField = value;
                this.RaisePropertyChanged("SlpPktBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string SlpPktEnd {
            get {
                return this.slpPktEndField;
            }
            set {
                this.slpPktEndField = value;
                this.RaisePropertyChanged("SlpPktEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SlpRanBegin {
            get {
                return this.slpRanBeginField;
            }
            set {
                this.slpRanBeginField = value;
                this.RaisePropertyChanged("SlpRanBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string SlpRanEnd {
            get {
                return this.slpRanEndField;
            }
            set {
                this.slpRanEndField = value;
                this.RaisePropertyChanged("SlpRanEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string VdBegin {
            get {
                return this.vdBeginField;
            }
            set {
                this.vdBeginField = value;
                this.RaisePropertyChanged("VdBegin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string VdComp {
            get {
                return this.vdCompField;
            }
            set {
                this.vdCompField = value;
                this.RaisePropertyChanged("VdComp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string VdEnd {
            get {
                return this.vdEndField;
            }
            set {
                this.vdEndField = value;
                this.RaisePropertyChanged("VdEnd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zopmscc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kokrsField;
        
        private string kostlField;
        
        private string ltextField;
        
        private string bkzkpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Kokrs {
            get {
                return this.kokrsField;
            }
            set {
                this.kokrsField = value;
                this.RaisePropertyChanged("Kokrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Kostl {
            get {
                return this.kostlField;
            }
            set {
                this.kostlField = value;
                this.RaisePropertyChanged("Kostl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Ltext {
            get {
                return this.ltextField;
            }
            set {
                this.ltextField = value;
                this.RaisePropertyChanged("Ltext");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Bkzkp {
            get {
                return this.bkzkpField;
            }
            set {
                this.bkzkpField = value;
                this.RaisePropertyChanged("Bkzkp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Bapiret2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string idField;
        
        private string numberField;
        
        private string messageField;
        
        private string logNoField;
        
        private string logMsgNoField;
        
        private string messageV1Field;
        
        private string messageV2Field;
        
        private string messageV3Field;
        
        private string messageV4Field;
        
        private string parameterField;
        
        private int rowField;
        
        private string fieldField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LogNo {
            get {
                return this.logNoField;
            }
            set {
                this.logNoField = value;
                this.RaisePropertyChanged("LogNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LogMsgNo {
            get {
                return this.logMsgNoField;
            }
            set {
                this.logMsgNoField = value;
                this.RaisePropertyChanged("LogMsgNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MessageV1 {
            get {
                return this.messageV1Field;
            }
            set {
                this.messageV1Field = value;
                this.RaisePropertyChanged("MessageV1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MessageV2 {
            get {
                return this.messageV2Field;
            }
            set {
                this.messageV2Field = value;
                this.RaisePropertyChanged("MessageV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MessageV3 {
            get {
                return this.messageV3Field;
            }
            set {
                this.messageV3Field = value;
                this.RaisePropertyChanged("MessageV3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MessageV4 {
            get {
                return this.messageV4Field;
            }
            set {
                this.messageV4Field = value;
                this.RaisePropertyChanged("MessageV4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
                this.RaisePropertyChanged("Parameter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
                this.RaisePropertyChanged("Row");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form= SysXml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("System");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zopmsvd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bukrsField;
        
        private string lifnrField;
        
        private string name1Field;
        
        private string loevmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Lifnr {
            get {
                return this.lifnrField;
            }
            set {
                this.lifnrField = value;
                this.RaisePropertyChanged("Lifnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
                this.RaisePropertyChanged("Name1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Loevm {
            get {
                return this.loevmField;
            }
            set {
                this.loevmField = value;
                this.RaisePropertyChanged("Loevm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zopmsslp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string zbukrsField;
        
        private string zkdrgiField;
        
        private string zkdrgnField;
        
        private string zkdpktField;
        
        private string zkdpk2Field;
        
        private string zthnpbField;
        
        private string zthptsField;
        
        private string zgpcosField;
        
        private string zpsnd1Field;
        
        private string zpsnd2Field;
        
        private string zpsnd3Field;
        
        private string zpsnd4Field;
        
        private string zpsnd5Field;
        
        private string zpsnd6Field;
        
        private string zthtmbField;
        
        private decimal zblpn2Field;
        
        private decimal zblot2Field;
        
        private string zpkpbgField;
        
        private string zththpField;
        
        private string zthmtmField;
        
        private decimal zjmltfField;
        
        private decimal zlkwtnField;
        
        private decimal zlskbhField;
        
        private decimal zlskbfField;
        
        private decimal zlskbpField;
        
        private string zjstnmField;
        
        private string zkdblkField;
        
        private string zjenkiField;
        
        private decimal zldltfField;
        
        private decimal zldltpField;
        
        private string zjsblkField;
        
        private string zjskwsField;
        
        private string zblpr3Field;
        
        private decimal zblkwuField;
        
        private decimal zblkwrField;
        
        private string ziofldField;
        
        private string ziofpmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Zbukrs {
            get {
                return this.zbukrsField;
            }
            set {
                this.zbukrsField = value;
                this.RaisePropertyChanged("Zbukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Zkdrgi {
            get {
                return this.zkdrgiField;
            }
            set {
                this.zkdrgiField = value;
                this.RaisePropertyChanged("Zkdrgi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Zkdrgn {
            get {
                return this.zkdrgnField;
            }
            set {
                this.zkdrgnField = value;
                this.RaisePropertyChanged("Zkdrgn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Zkdpkt {
            get {
                return this.zkdpktField;
            }
            set {
                this.zkdpktField = value;
                this.RaisePropertyChanged("Zkdpkt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string Zkdpk2 {
            get {
                return this.zkdpk2Field;
            }
            set {
                this.zkdpk2Field = value;
                this.RaisePropertyChanged("Zkdpk2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string Zthnpb {
            get {
                return this.zthnpbField;
            }
            set {
                this.zthnpbField = value;
                this.RaisePropertyChanged("Zthnpb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Zthpts {
            get {
                return this.zthptsField;
            }
            set {
                this.zthptsField = value;
                this.RaisePropertyChanged("Zthpts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string Zgpcos {
            get {
                return this.zgpcosField;
            }
            set {
                this.zgpcosField = value;
                this.RaisePropertyChanged("Zgpcos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string Zpsnd1 {
            get {
                return this.zpsnd1Field;
            }
            set {
                this.zpsnd1Field = value;
                this.RaisePropertyChanged("Zpsnd1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string Zpsnd2 {
            get {
                return this.zpsnd2Field;
            }
            set {
                this.zpsnd2Field = value;
                this.RaisePropertyChanged("Zpsnd2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string Zpsnd3 {
            get {
                return this.zpsnd3Field;
            }
            set {
                this.zpsnd3Field = value;
                this.RaisePropertyChanged("Zpsnd3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string Zpsnd4 {
            get {
                return this.zpsnd4Field;
            }
            set {
                this.zpsnd4Field = value;
                this.RaisePropertyChanged("Zpsnd4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string Zpsnd5 {
            get {
                return this.zpsnd5Field;
            }
            set {
                this.zpsnd5Field = value;
                this.RaisePropertyChanged("Zpsnd5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string Zpsnd6 {
            get {
                return this.zpsnd6Field;
            }
            set {
                this.zpsnd6Field = value;
                this.RaisePropertyChanged("Zpsnd6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string Zthtmb {
            get {
                return this.zthtmbField;
            }
            set {
                this.zthtmbField = value;
                this.RaisePropertyChanged("Zthtmb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal Zblpn2 {
            get {
                return this.zblpn2Field;
            }
            set {
                this.zblpn2Field = value;
                this.RaisePropertyChanged("Zblpn2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal Zblot2 {
            get {
                return this.zblot2Field;
            }
            set {
                this.zblot2Field = value;
                this.RaisePropertyChanged("Zblot2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string Zpkpbg {
            get {
                return this.zpkpbgField;
            }
            set {
                this.zpkpbgField = value;
                this.RaisePropertyChanged("Zpkpbg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string Zththp {
            get {
                return this.zththpField;
            }
            set {
                this.zththpField = value;
                this.RaisePropertyChanged("Zththp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string Zthmtm {
            get {
                return this.zthmtmField;
            }
            set {
                this.zthmtmField = value;
                this.RaisePropertyChanged("Zthmtm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public decimal Zjmltf {
            get {
                return this.zjmltfField;
            }
            set {
                this.zjmltfField = value;
                this.RaisePropertyChanged("Zjmltf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public decimal Zlkwtn {
            get {
                return this.zlkwtnField;
            }
            set {
                this.zlkwtnField = value;
                this.RaisePropertyChanged("Zlkwtn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public decimal Zlskbh {
            get {
                return this.zlskbhField;
            }
            set {
                this.zlskbhField = value;
                this.RaisePropertyChanged("Zlskbh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public decimal Zlskbf {
            get {
                return this.zlskbfField;
            }
            set {
                this.zlskbfField = value;
                this.RaisePropertyChanged("Zlskbf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public decimal Zlskbp {
            get {
                return this.zlskbpField;
            }
            set {
                this.zlskbpField = value;
                this.RaisePropertyChanged("Zlskbp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string Zjstnm {
            get {
                return this.zjstnmField;
            }
            set {
                this.zjstnmField = value;
                this.RaisePropertyChanged("Zjstnm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string Zkdblk {
            get {
                return this.zkdblkField;
            }
            set {
                this.zkdblkField = value;
                this.RaisePropertyChanged("Zkdblk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string Zjenki {
            get {
                return this.zjenkiField;
            }
            set {
                this.zjenkiField = value;
                this.RaisePropertyChanged("Zjenki");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public decimal Zldltf {
            get {
                return this.zldltfField;
            }
            set {
                this.zldltfField = value;
                this.RaisePropertyChanged("Zldltf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public decimal Zldltp {
            get {
                return this.zldltpField;
            }
            set {
                this.zldltpField = value;
                this.RaisePropertyChanged("Zldltp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string Zjsblk {
            get {
                return this.zjsblkField;
            }
            set {
                this.zjsblkField = value;
                this.RaisePropertyChanged("Zjsblk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string Zjskws {
            get {
                return this.zjskwsField;
            }
            set {
                this.zjskwsField = value;
                this.RaisePropertyChanged("Zjskws");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string Zblpr3 {
            get {
                return this.zblpr3Field;
            }
            set {
                this.zblpr3Field = value;
                this.RaisePropertyChanged("Zblpr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public decimal Zblkwu {
            get {
                return this.zblkwuField;
            }
            set {
                this.zblkwuField = value;
                this.RaisePropertyChanged("Zblkwu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public decimal Zblkwr {
            get {
                return this.zblkwrField;
            }
            set {
                this.zblkwrField = value;
                this.RaisePropertyChanged("Zblkwr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string Ziofld {
            get {
                return this.ziofldField;
            }
            set {
                this.ziofldField = value;
                this.RaisePropertyChanged("Ziofld");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string Ziofpm {
            get {
                return this.ziofpmField;
            }
            set {
                this.ziofpmField = value;
                this.RaisePropertyChanged("Ziofpm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zopmsgl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bukrsField;
        
        private string saknrField;
        
        private string txt50Field;
        
        private string xloebField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Saknr {
            get {
                return this.saknrField;
            }
            set {
                this.saknrField = value;
                this.RaisePropertyChanged("Saknr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Txt50 {
            get {
                return this.txt50Field;
            }
            set {
                this.txt50Field = value;
                this.RaisePropertyChanged("Txt50");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Xloeb {
            get {
                return this.xloebField;
            }
            set {
                this.xloebField = value;
                this.RaisePropertyChanged("Xloeb");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class Zopmscs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bukrsField;
        
        private string kunnrField;
        
        private string name1Field;
        
        private string loevmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Bukrs {
            get {
                return this.bukrsField;
            }
            set {
                this.bukrsField = value;
                this.RaisePropertyChanged("Bukrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Kunnr {
            get {
                return this.kunnrField;
            }
            set {
                this.kunnrField = value;
                this.RaisePropertyChanged("Kunnr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Name1 {
            get {
                return this.name1Field;
            }
            set {
                this.name1Field = value;
                this.RaisePropertyChanged("Name1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string Loevm {
            get {
                return this.loevmField;
            }
            set {
                this.loevmField = value;
                this.RaisePropertyChanged("Loevm");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZfmOpmsMasterResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Zopmscc[] itCcField;
        
        private Zopmscs[] itCustField;
        
        private Zopmsgl[] itGlField;
        
        private Zopmsslp[] itSlpField;
        
        private Zopmsvd[] itVendField;
        
        private Bapiret2[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmscc[] ItCc {
            get {
                return this.itCcField;
            }
            set {
                this.itCcField = value;
                this.RaisePropertyChanged("ItCc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmscs[] ItCust {
            get {
                return this.itCustField;
            }
            set {
                this.itCustField = value;
                this.RaisePropertyChanged("ItCust");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmsgl[] ItGl {
            get {
                return this.itGlField;
            }
            set {
                this.itGlField = value;
                this.RaisePropertyChanged("ItGl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmsslp[] ItSlp {
            get {
                return this.itSlpField;
            }
            set {
                this.itSlpField = value;
                this.RaisePropertyChanged("ItSlp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Zopmsvd[] ItVend {
            get {
                return this.itVendField;
            }
            set {
                this.itVendField = value;
                this.RaisePropertyChanged("ItVend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Bapiret2[] Return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("Return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmOpmsMasterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMaster ZfmOpmsMaster;
        
        public ZfmOpmsMasterRequest() {
        }
        
        public ZfmOpmsMasterRequest(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMaster ZfmOpmsMaster) {
            this.ZfmOpmsMaster = ZfmOpmsMaster;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZfmOpmsMasterResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style", Order=0)]
        public MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse ZfmOpmsMasterResponse;
        
        public ZfmOpmsMasterResponse1() {
        }
        
        public ZfmOpmsMasterResponse1(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse ZfmOpmsMasterResponse) {
            this.ZfmOpmsMasterResponse = ZfmOpmsMasterResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_OPMS_MASTERChannel : MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_OPMS_MASTERClient : System.ServiceModel.ClientBase<MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER>, MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER {
        
        public ZWS_OPMS_MASTERClient() {
        }
        
        public ZWS_OPMS_MASTERClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_OPMS_MASTERClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_OPMS_MASTERClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_OPMS_MASTERClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse1 MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER.ZfmOpmsMaster(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest request) {
            return base.Channel.ZfmOpmsMaster(request);
        }
        
        public MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse ZfmOpmsMaster(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMaster ZfmOpmsMaster1) {
            MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest inValue = new MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest();
            inValue.ZfmOpmsMaster = ZfmOpmsMaster1;
            MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse1 retVal = ((MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER)(this)).ZfmOpmsMaster(inValue);
            return retVal.ZfmOpmsMasterResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse1> MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER.ZfmOpmsMasterAsync(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest request) {
            return base.Channel.ZfmOpmsMasterAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterResponse1> ZfmOpmsMasterAsync(MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMaster ZfmOpmsMaster) {
            MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest inValue = new MVC_SYSTEM.SAPMD_FLP.ZfmOpmsMasterRequest();
            inValue.ZfmOpmsMaster = ZfmOpmsMaster;
            return ((MVC_SYSTEM.SAPMD_FLP.ZWS_OPMS_MASTER)(this)).ZfmOpmsMasterAsync(inValue);
        }
    }
}
